### ISSUE TITLE
Pushing this code to conv_emotion?

### ISSUE THREAD

**Issue by soujanyaporia** [mianzhang/dialogue_gcn#1]
Hi! 

Great work :) Thank you so much!

Would you mind to push this version to our conv_emotion repo? - https://github.com/declare-lab/conv-emotion/tree/master/DialogueGCN

Of course, we will give you the credit, citation, your GitHub profile link.

Let me know, please.

Thanks!

Regards,
Soujanya

**Comment by mianzhang** [comment]
> Hi!
> 
> Great work :) Thank you so much!
> 
> Would you mind to push this version to our conv_emotion repo? - https://github.com/declare-lab/conv-emotion/tree/master/DialogueGCN
> 
> Of course, we will give you the credit, citation, your GitHub profile link.
> 
> Let me know, please.
> 
> Thanks!
> 
> Regards,
> Soujanya

It's my pleasure, but how to do it, you directly add the codes?

**Comment by soujanyaporia** [comment]
Thanks! I think just do a PR to the conv-emotion repo (pull request). 

Btw we got an error while running the code; please see attached. 
![WhatsApp Image 2020-07-25 at 19 53 33](https://user-images.githubusercontent.com/40890991/88458470-dd4bda80-cec0-11ea-9311-fbad4b334f94.jpeg)

**Comment by mianzhang** [comment]
> Thanks! I think just do a PR to the conv-emotion repo (pull request).
> 
> Btw we got an error while running the code; please see attached.
> ![WhatsApp Image 2020-07-25 at 19 53 33](https://user-images.githubusercontent.com/40890991/88458470-dd4bda80-cec0-11ea-9311-fbad4b334f94.jpeg)

I can successfully run my codes in my machine. You can see the "self.conv1" layer in GCN.py is just the same as the original codes of DialogueGCN, which is an RGCNConv layer provided by Pytorch Geometric. I have no idea about your error now. Sorry.
![image](https://user-images.githubusercontent.com/31158330/88459160-c78ce400-cec5-11ea-8212-32f5d5daf921.png)

**Comment by soujanyaporia** [comment]
Thanks! I think this is because of pytorch geometric package's version. We should use 1.3.0. Please PR to conv_emotion when you get time :)

**Comment by mianzhang** [comment]
👌

**Comment by soujanyaporia** [comment]
The code runs very well. Far better implementation than the original! Very good work. Congratulations! :) Please feel free to PR to conv_emotion. Thank you!

**Comment by mianzhang** [comment]
How do I name the project folder?

**Comment by soujanyaporia** [comment]
I think You can create a subdir under DialogueGCN?
Say DialogueGCN_mianzhang

**Comment by soujanyaporia** [comment]
Or just under conv_emotion you create a folder called DialogueGCN_mianzhang

**Comment by DesmonDay** [comment]
Hi, @soujanyaporia 
I have a question about reproducing the results using this code. I run the code and only get F1 58.01% for test set. I wonder how you reproduce the results and get the conclusion of "far better implementation than the original"? Can you tell me what should I pay attention to? So many thanks!!
