### ISSUE TITLE
Some questions about the GCN part of the code

### ISSUE THREAD

**Issue by zjyyyy** [mianzhang/dialogue_gcn#2]
I encountered some problems when reproducing the code. The parameters on line 14 in dgcn/model/GCN.py seem to have some problems. What is the correct setting here? Thank you very much for opening source this work.

**Comment by zjyyyy** [comment]
It may be caused by the version of the package. Could you open the requirements file?

**Comment by DesmonDay** [comment]
Hi, do you know where to download the corresponding dataset? I have downloaded one version, but it seems something wrong.

**Comment by zjyyyy** [comment]
https://github.com/SenticNet/conv-emotion

**Comment by DesmonDay** [comment]
thank you~

**Comment by zjyyyy** [comment]
> thank you~

Can you reproduce the result of F1=64.10% on IEMOCAP dataset？

**Comment by mianzhang** [comment]
done

**Comment by DesmonDay** [comment]
No. I only get 0.5801 for testset F1.
