### ISSUE TITLE
Not able to reproduce the results

### ISSUE THREAD

**Issue by DesmonDay** [mianzhang/dialogue_gcn#3]
Hi. I follow the same procedure in your README. But got a F1 result of test set as 0.5801. 
Can you tell me what may I do wrong?

**Comment by DesmonDay** [comment]
Besides, can you provide the dataset? I directly use the data features in conv_emotion repository. But it seems different for the data size.

**Comment by DesmonDay** [comment]
Hope the author can answer me.... @mianzhang

**Comment by mianzhang** [comment]
I can get 62+% f1 on average on my machine.

**Comment by DesmonDay** [comment]
Did you use other parameter settings? I can paste my results here. 
![image](https://user-images.githubusercontent.com/20554008/92565347-14c5e900-f2ad-11ea-8c35-0056267f6120.png)

**Comment by mianzhang** [comment]
No, I just run the codes as described in the repo.

**Comment by DesmonDay** [comment]
Me did the same too...  ok, I will not reference your code.
