### ISSUE TITLE
PLz！how does the dataset work？

### ISSUE THREAD

**Issue by cccxyc** [mianzhang/dialogue_gcn#4]
i have downloaded iemocap yet found no pkl for utils to load_pkl.
 is there any necessary process missing ?
.first time  using this dataset

**Comment by mianzhang** [comment]
Just go to https://github.com/declare-lab/conv-emotion

**Comment by mianzhang** [comment]
https://github.com/declare-lab/conv-emotion/blob/master/DialogueGCN/IEMOCAP_features/IEMOCAP_features.pkl
